### ISSUE TITLE
Is this still required in ios9

### ISSUE THREAD

**Issue by awebdeveloper** [Telerik-Verified-Plugins/WKWebView#174] opened 2015-10-04 09:54 UTC
since file://url is fixed in ios9 do i need to use this in ios9

**Comment by EddyVerbruggen** [comment] 2015-10-04 18:54
You mean this plugin?

**Comment by EddyVerbruggen** [comment] 2015-10-04 18:56
Aha, dupe of your question in #127.

**Closed by EddyVerbruggen** 2015-10-04 18:56 UTC
