### ISSUE TITLE
cordova-plugin-code-push not working

### ISSUE THREAD

**Issue by naviocean** [Telerik-Verified-Plugins/WKWebView#216] opened 2016-01-21 16:59 UTC
Dear Sir,
I got an issue that WKWebView does not compatible with https://github.com/Microsoft/cordova-plugin-code-push#getting-started
Here is my testing app: https://dl.dropboxusercontent.com/u/9705556/codePush.zip
Thanks

**Comment by tropperstyle** [comment] 2016-01-30 01:58
I am looking to mix these two plugins as well. Are there any more details on exactly what goes wrong and a potential fix?

**Comment by naviocean** [comment] 2016-01-30 14:01
I'm not sure but I think may be Code Push can not access file while using WKWebView

**Comment by clauderic** [comment] 2016-05-02 18:45
Same issue here:

Code push is trying to access a file:// url... Something along the lines of:
```
http://localhost:12344/file:///Library/NoCloud/codepush/deploy/versions/76947cf4da08b6be904cd20956bc2796031b2f260c86420f602d7e936475b23c/www/index.html
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by northkode** [comment] 2016-07-07 01:39
The issue is the code-push plugin redirects the url of the webview to a local folder inside the application directory when it has installed a new hot fix. this folder looks like this 

http://localhost:12344/file:///Users/username/Library/Developer/CoreSimulator/Devices/uuid/data/Containers/Data/Application/application-id/Library/NoCloud/codepush/deploy/versions/version-hash/www/index.html

as you can see its file:/// and then the path.. 
if some how we can have the server restart with a new directoryPath instead of the one in myMainViewController.wwwFolderName or have that plugin set that value and restart the server when you install a new code-push

**Comment by silhouettes** [comment] 2016-07-07 18:14
As an update for others, according to https://github.com/Microsoft/cordova-plugin-code-push/issues/134#issuecomment-230967470 this issue might be resolved by updating to the latest version :)

**Comment by northkode** [comment] 2016-07-07 18:19
Yes, I have confirmed the lastest version is working fully for code-push in our build on app store for IOS

**Closed** 2016-08-23 11:29 UTC
